"""supabase auth: link + nullable creds

Revision ID: 1f5b209d190b
Revises: c79d070a7c0f
Create Date: 2026-06-14 00:30:47.128293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5b209d190b'
down_revision: Union[str, None] = 'c79d070a7c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_user_id', sa.String(length=64), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_supabase_user_id'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('supabase_user_id')

    # ### end Alembic commands ###
